# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from intelli_hr_python_sdk import schemas  # noqa: F401


class WebhookEventScheduled(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            scheduled_for = schemas.StrSchema
            scheduled_offset = schemas.StrSchema
            __annotations__ = {
                "scheduled_for": scheduled_for,
                "scheduled_offset": scheduled_offset,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheduled_for"]) -> MetaOapg.properties.scheduled_for: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheduled_offset"]) -> MetaOapg.properties.scheduled_offset: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["scheduled_for", "scheduled_offset", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheduled_for"]) -> typing.Union[MetaOapg.properties.scheduled_for, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheduled_offset"]) -> typing.Union[MetaOapg.properties.scheduled_offset, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["scheduled_for", "scheduled_offset", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        scheduled_for: typing.Union[MetaOapg.properties.scheduled_for, str, schemas.Unset] = schemas.unset,
        scheduled_offset: typing.Union[MetaOapg.properties.scheduled_offset, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'WebhookEventScheduled':
        return super().__new__(
            cls,
            *args,
            scheduled_for=scheduled_for,
            scheduled_offset=scheduled_offset,
            _configuration=_configuration,
            **kwargs,
        )
