# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from intelli_hr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from intelli_hr_python_sdk.api_response import AsyncGeneratorResponse
from intelli_hr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from intelli_hr_python_sdk import schemas  # noqa: F401

from intelli_hr_python_sdk.model.job_requirement_groups_create_request import JobRequirementGroupsCreateRequest as JobRequirementGroupsCreateRequestSchema
from intelli_hr_python_sdk.model.job_requirement_groups_create_request_library_item_ids import JobRequirementGroupsCreateRequestLibraryItemIds as JobRequirementGroupsCreateRequestLibraryItemIdsSchema
from intelli_hr_python_sdk.model.job_requirement_groups import JobRequirementGroups as JobRequirementGroupsSchema

from intelli_hr_python_sdk.type.job_requirement_groups_create_request_library_item_ids import JobRequirementGroupsCreateRequestLibraryItemIds
from intelli_hr_python_sdk.type.job_requirement_groups_create_request import JobRequirementGroupsCreateRequest
from intelli_hr_python_sdk.type.job_requirement_groups import JobRequirementGroups

from ...api_client import Dictionary
from intelli_hr_python_sdk.pydantic.job_requirement_groups import JobRequirementGroups as JobRequirementGroupsPydantic
from intelli_hr_python_sdk.pydantic.job_requirement_groups_create_request_library_item_ids import JobRequirementGroupsCreateRequestLibraryItemIds as JobRequirementGroupsCreateRequestLibraryItemIdsPydantic
from intelli_hr_python_sdk.pydantic.job_requirement_groups_create_request import JobRequirementGroupsCreateRequest as JobRequirementGroupsCreateRequestPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = JobRequirementGroupsCreateRequestSchema


request_body_job_requirement_groups_create_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'ApiKey',
]
SchemaFor201ResponseBodyApplicationJson = JobRequirementGroupsSchema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: JobRequirementGroups


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: JobRequirementGroups


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
)


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
)


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
)
_status_code_to_response = {
    '201': _response_for_201,
    '400': _response_for_400,
    '403': _response_for_403,
    '500': _response_for_500,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_new_group_mapped_args(
        self,
        name: str,
        library_item_ids: JobRequirementGroupsCreateRequestLibraryItemIds,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if name is not None:
            _body["name"] = name
        if library_item_ids is not None:
            _body["libraryItemIds"] = library_item_ids
        args.body = _body
        return args

    async def _acreate_new_group_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create a new Job Requirement Group
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/job-requirement-groups',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_job_requirement_groups_create_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_new_group_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create a new Job Requirement Group
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/job-requirement-groups',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_job_requirement_groups_create_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateNewGroupRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_new_group(
        self,
        name: str,
        library_item_ids: JobRequirementGroupsCreateRequestLibraryItemIds,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_group_mapped_args(
            name=name,
            library_item_ids=library_item_ids,
        )
        return await self._acreate_new_group_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_new_group(
        self,
        name: str,
        library_item_ids: JobRequirementGroupsCreateRequestLibraryItemIds,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_group_mapped_args(
            name=name,
            library_item_ids=library_item_ids,
        )
        return self._create_new_group_oapg(
            body=args.body,
        )

class CreateNewGroup(BaseApi):

    async def acreate_new_group(
        self,
        name: str,
        library_item_ids: JobRequirementGroupsCreateRequestLibraryItemIds,
        validate: bool = False,
        **kwargs,
    ) -> JobRequirementGroupsPydantic:
        raw_response = await self.raw.acreate_new_group(
            name=name,
            library_item_ids=library_item_ids,
            **kwargs,
        )
        if validate:
            return JobRequirementGroupsPydantic(**raw_response.body)
        return api_client.construct_model_instance(JobRequirementGroupsPydantic, raw_response.body)
    
    
    def create_new_group(
        self,
        name: str,
        library_item_ids: JobRequirementGroupsCreateRequestLibraryItemIds,
        validate: bool = False,
    ) -> JobRequirementGroupsPydantic:
        raw_response = self.raw.create_new_group(
            name=name,
            library_item_ids=library_item_ids,
        )
        if validate:
            return JobRequirementGroupsPydantic(**raw_response.body)
        return api_client.construct_model_instance(JobRequirementGroupsPydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        name: str,
        library_item_ids: JobRequirementGroupsCreateRequestLibraryItemIds,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_group_mapped_args(
            name=name,
            library_item_ids=library_item_ids,
        )
        return await self._acreate_new_group_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        name: str,
        library_item_ids: JobRequirementGroupsCreateRequestLibraryItemIds,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_group_mapped_args(
            name=name,
            library_item_ids=library_item_ids,
        )
        return self._create_new_group_oapg(
            body=args.body,
        )

