# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

import unittest

import intelli_hr_python_sdk
from intelli_hr_python_sdk.model.trainings_create_request_job import TrainingsCreateRequestJob
from intelli_hr_python_sdk import configuration


class TestTrainingsCreateRequestJob(unittest.TestCase):
    """TrainingsCreateRequestJob unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
