# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

import unittest

import intelli_hr_python_sdk
from intelli_hr_python_sdk.model.person_id_image_create_response_meta import PersonIdImageCreateResponseMeta
from intelli_hr_python_sdk import configuration


class TestPersonIdImageCreateResponseMeta(unittest.TestCase):
    """PersonIdImageCreateResponseMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
