# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

import unittest

import intelli_hr_python_sdk
from intelli_hr_python_sdk.model.custom_field_definition_patch_request_select_definition_options import CustomFieldDefinitionPatchRequestSelectDefinitionOptions
from intelli_hr_python_sdk import configuration


class TestCustomFieldDefinitionPatchRequestSelectDefinitionOptions(unittest.TestCase):
    """CustomFieldDefinitionPatchRequestSelectDefinitionOptions unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
