# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from intelli_hr_python_sdk.pydantic.custom_fields_response import CustomFieldsResponse

class BusinessUnitsData(BaseModel):
    # The identifier string for the [Business Unit](https://developers.intellihr.io/docs/v1/).
    id: typing.Optional[str] = Field(None, alias='id')

    # Optional identifier that can be used for administrative tasks.
    identifier: typing.Optional[str] = Field(None, alias='identifier')

    # Name given to this [Business Unit](https://developers.intellihr.io/docs/v1/). This name would normally be shown to users of the system.
    name: typing.Optional[str] = Field(None, alias='name')

    # Code given to this [Business Unit](https://developers.intellihr.io/docs/v1/)
    code: typing.Optional[str] = Field(None, alias='code')

    # Notes attached to a [Business Unit](https://developers.intellihr.io/docs/v1/)
    notes: typing.Optional[str] = Field(None, alias='notes')

    # The identifier string for the parent [Business Unit](https://developers.intellihr.io/docs/v1/), or null if there is no parent (this is a top level business unit).
    parent_id: typing.Optional[typing.Union[str, none_type]] = Field(None, alias='parentId')

    # Specifies whether users can select this [Business Unit](https://developers.intellihr.io/docs/v1/) in dropdowns.
    is_enabled: typing.Optional[bool] = Field(None, alias='isEnabled')

    # The custom field values for this [Business Unit](https://developers.intellihr.io/docs/v1/)
    custom_fields: typing.Optional[CustomFieldsResponse] = Field(None, alias='customFields')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
