# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from intelli_hr_python_sdk.pydantic.job_create_request_recruitment_source import JobCreateRequestRecruitmentSource

class JobCreateRequestRecruitment(BaseModel):
    source: typing.Optional[JobCreateRequestRecruitmentSource] = Field(None, alias='source')

    # The cost of the recruitment. Any number exceeding 8 decimal places will be rounded up.
    cost: typing.Optional[typing.Union[int, float]] = Field(None, alias='cost')

    # The currency used to recruit this [Job](https://developers.intellihr.io/docs/v1/). An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).
    currency: typing.Optional[str] = Field(None, alias='currency')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
