# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PersonIdImageCreateResponseDataFields(BaseModel):
    x-amz-server-side-encryption_: typing.Optional[str] = Field(None, alias='x-amz-server-side-encryption')

    key: typing.Optional[str] = Field(None, alias='key')

    a_w_s_access_key_id: typing.Optional[str] = Field(None, alias='AWSAccessKeyId')

    x-amz-security-token_: typing.Optional[str] = Field(None, alias='x-amz-security-token')

    policy: typing.Optional[str] = Field(None, alias='policy')

    signature: typing.Optional[str] = Field(None, alias='signature')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
