# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from intelli_hr_python_sdk.pydantic.workflows_patch_request_workflow_form_designs import WorkflowsPatchRequestWorkflowFormDesigns

class WorkflowsPatchRequest(BaseModel):
    # The identifier string for the [Job](https://developers.intellihr.io/docs/v1/) to trigger this Workflow for.
    job_id: str = Field(alias='jobId')

    workflow_form_designs: WorkflowsPatchRequestWorkflowFormDesigns = Field(alias='workflowFormDesigns')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
