# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBusinessEntitiesCreateNewEntity403Response(TypedDict):
    pass

class OptionalBusinessEntitiesCreateNewEntity403Response(TypedDict, total=False):
    name: str

    message: str

    # HTTP Status Code for the error.
    code: int

    errors: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class BusinessEntitiesCreateNewEntity403Response(RequiredBusinessEntitiesCreateNewEntity403Response, OptionalBusinessEntitiesCreateNewEntity403Response):
    pass
