# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.custom_field_definitions_list_data import CustomFieldDefinitionsListData
from intelli_hr_python_sdk.type.custom_field_definitions_list_links import CustomFieldDefinitionsListLinks
from intelli_hr_python_sdk.type.custom_field_definitions_list_meta import CustomFieldDefinitionsListMeta

class RequiredCustomFieldDefinitionsList(TypedDict):
    pass

class OptionalCustomFieldDefinitionsList(TypedDict, total=False):
    data: CustomFieldDefinitionsListData

    meta: CustomFieldDefinitionsListMeta

    links: CustomFieldDefinitionsListLinks

class CustomFieldDefinitionsList(RequiredCustomFieldDefinitionsList, OptionalCustomFieldDefinitionsList):
    pass
