# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.forms_data_document_uploads import FormsDataDocumentUploads
from intelli_hr_python_sdk.type.forms_data_form_design import FormsDataFormDesign
from intelli_hr_python_sdk.type.forms_data_subject import FormsDataSubject

class RequiredFormsData(TypedDict):
    pass

class OptionalFormsData(TypedDict, total=False):
    # The identifier string for the [Form](https://developers.intellihr.io/docs/v1/).
    id: str

    # The date this [Form](https://developers.intellihr.io/docs/v1/) was issued to the recipient. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
    issueDate: str

    # The due date for the recipient to complete this [Form](https://developers.intellihr.io/docs/v1/). This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
    dueDate: typing.Union[str, none_type]

    # The date a reminder notification will be sent out for this [Form](https://developers.intellihr.io/docs/v1/) if uncompleted. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
    reminderDate: typing.Union[str, none_type]

    # The authorization code required to access this form via a url.
    accessCode: str

    # The date this [Form](https://developers.intellihr.io/docs/v1/) was completed. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
    completedAt: typing.Union[str, none_type]

    formDesign: FormsDataFormDesign

    subject: FormsDataSubject

    # The expected respondent for this [Form](https://developers.intellihr.io/docs/v1/)
    respondent: typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]], none_type]

    # The person who submitted this [Form](https://developers.intellihr.io/docs/v1/), note that this can be different from the expected respondent. If this form has not been ccompleted, this will be null
    submitter: typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]], none_type]

    # An array of answers for this [Form](https://developers.intellihr.io/docs/v1/).  If this form has not been completed, this field will be null.
    answers: typing.Union[typing.List[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]], none_type]

    documentUploads: FormsDataDocumentUploads

    # WARNING: This property is deprecated
    # [Job](https://developers.intellihr.io/docs/v1/) to whom this [Form](https://developers.intellihr.io/docs/v1/) expects a response from. This job value has been deprecated, you should now reference the job object within the respondent field.
    job: typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]], none_type]

    # WARNING: This property is deprecated
    # [Person](https://developers.intellihr.io/docs/v1/) to whom this [Form](https://developers.intellihr.io/docs/v1/) expects a response from. Note that this person value has been deprecated, you should now reference the person object within the respondent field.
    person: typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]], none_type]

class FormsData(RequiredFormsData, OptionalFormsData):
    pass
