# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredFormsDataSubjectJob(TypedDict):
    pass

class OptionalFormsDataSubjectJob(TypedDict, total=False):
    # The identifier string for the [Job](https://developers.intellihr.io/docs/v1/).
    id: str

    # The name/position title of this [Job](https://developers.intellihr.io/docs/v1/).
    name: str

    # Link on the public api to get more information on this piece of data.
    link: str

class FormsDataSubjectJob(RequiredFormsDataSubjectJob, OptionalFormsDataSubjectJob):
    pass
