# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobPatchResponseDataPayGrade(TypedDict):
    pass

class OptionalJobPatchResponseDataPayGrade(TypedDict, total=False):
    # The identifier string for the [Pay Grade](https://developers.intellihr.io/docs/v1/) of this [Job](https://developers.intellihr.io/docs/v1/).
    id: str

    # User friendly name given to the [Pay Grade](https://developers.intellihr.io/docs/v1/).
    name: str

    # Administrative, short code associated to the [Pay Grade](https://developers.intellihr.io/docs/v1/).
    code: str

    payStep: typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]], none_type]

    # Link on the public api to get more information on this piece of data.
    link: str

class JobPatchResponseDataPayGrade(RequiredJobPatchResponseDataPayGrade, OptionalJobPatchResponseDataPayGrade):
    pass
