# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.job_requirement_groups_data_library_items import JobRequirementGroupsDataLibraryItems

class RequiredJobRequirementGroupsData(TypedDict):
    pass

class OptionalJobRequirementGroupsData(TypedDict, total=False):
    # The identifier string for the [Job Requirement Group](https://developers.intellihr.io/docs/v1/).
    id: str

    # The issue date of the [Job Requirement Group](https://developers.intellihr.io/docs/v1/)
    name: str

    libraryItems: JobRequirementGroupsDataLibraryItems

    # The count of how many times this job requirement group is being used in job requirements
    jobRequirementUsageCount: typing.Union[int, float]

class JobRequirementGroupsData(RequiredJobRequirementGroupsData, OptionalJobRequirementGroupsData):
    pass
