# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobChangeReasonsPatchRequest(TypedDict):
    pass

class OptionalJobChangeReasonsPatchRequest(TypedDict, total=False):
    # Name given to this [Job Change Reason](https://developers.intellihr.io/docs/v1/). This name would normally be shown to users of the system.
    name: str

    # Specifies whether users can select this [Job Change Reason](https://developers.intellihr.io/docs/v1/) in dropdowns.
    isEnabled: bool

class JobChangeReasonsPatchRequest(RequiredJobChangeReasonsPatchRequest, OptionalJobChangeReasonsPatchRequest):
    pass
