# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.job_patch_request_business_entity import JobPatchRequestBusinessEntity
from intelli_hr_python_sdk.type.job_patch_request_business_unit import JobPatchRequestBusinessUnit
from intelli_hr_python_sdk.type.job_patch_request_custom_fields import JobPatchRequestCustomFields
from intelli_hr_python_sdk.type.job_patch_request_employment_condition import JobPatchRequestEmploymentCondition
from intelli_hr_python_sdk.type.job_patch_request_establishment import JobPatchRequestEstablishment
from intelli_hr_python_sdk.type.job_patch_request_job_change_reason import JobPatchRequestJobChangeReason
from intelli_hr_python_sdk.type.job_patch_request_location import JobPatchRequestLocation
from intelli_hr_python_sdk.type.job_patch_request_pay_grade import JobPatchRequestPayGrade
from intelli_hr_python_sdk.type.job_patch_request_remuneration_schedule import JobPatchRequestRemunerationSchedule
from intelli_hr_python_sdk.type.job_patch_request_supervisor_job import JobPatchRequestSupervisorJob
from intelli_hr_python_sdk.type.job_patch_request_supervisor_person import JobPatchRequestSupervisorPerson
from intelli_hr_python_sdk.type.job_patch_request_work_class import JobPatchRequestWorkClass
from intelli_hr_python_sdk.type.job_patch_request_work_type import JobPatchRequestWorkType

class RequiredJobPatchRequest(TypedDict):
    # The date this [Job](https://developers.intellihr.io/docs/v1/) Update is effective from within the organisation. Note that this doesn't affect the start date of the overall job itself. A `null` value will indicate that this Update is effective from the start of the [Job](https://developers.intellihr.io/docs/v1/). This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).   YYYY-MM-DD date formatting is also supported, although by using this format the date will be stored as the start of day in UTC time, not the requesting tenants timezone.
    effectiveFrom: typing.Union[str, none_type]

class OptionalJobPatchRequest(TypedDict, total=False):
    # The date this [Job](https://developers.intellihr.io/docs/v1/) Update is effective to within the organisation. Note that this doesn't affect the end date of the overall job itself. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).   YYYY-MM-DD date formatting is also supported, although by using this format the date will be stored as the start of day in UTC time, not the requesting tenants timezone.
    effectiveTo: str

    # The job name to be updated. Will attempt to match to an existing [Position Title](https://developers.intellihr.io/docs/v1/), otherwise creates a new [Position Title](https://developers.intellihr.io/docs/v1/).
    name: str

    businessEntity: JobPatchRequestBusinessEntity

    businessUnit: JobPatchRequestBusinessUnit

    establishment: JobPatchRequestEstablishment

    jobChangeReason: JobPatchRequestJobChangeReason

    supervisorPerson: JobPatchRequestSupervisorPerson

    supervisorJob: JobPatchRequestSupervisorJob

    location: JobPatchRequestLocation

    workClass: JobPatchRequestWorkClass

    workType: JobPatchRequestWorkType

    # The full time equivalent of this [Job](https://developers.intellihr.io/docs/v1/). Indicating the workload of an employee that can be comparable across different contexts. This is null for people without an FTE.
    fte: str

    payGrade: JobPatchRequestPayGrade

    employmentCondition: JobPatchRequestEmploymentCondition

    remunerationSchedule: JobPatchRequestRemunerationSchedule

    customFields: JobPatchRequestCustomFields

class JobPatchRequest(RequiredJobPatchRequest, OptionalJobPatchRequest):
    pass
