# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.job_create_request_recruitment_source import JobCreateRequestRecruitmentSource

class RequiredJobCreateRequestRecruitment(TypedDict):
    pass

class OptionalJobCreateRequestRecruitment(TypedDict, total=False):
    source: JobCreateRequestRecruitmentSource

    # The cost of the recruitment. Any number exceeding 8 decimal places will be rounded up.
    cost: typing.Union[int, float]

    # The currency used to recruit this [Job](https://developers.intellihr.io/docs/v1/). An international currency code. Typically AUD for Australian dollar, USD for American dollar etc. See [Official list of codes](https://www.iban.com/currency-codes).
    currency: str

class JobCreateRequestRecruitment(RequiredJobCreateRequestRecruitment, OptionalJobCreateRequestRecruitment):
    pass
