# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobPatchResponseMeta(TypedDict):
    pass

class OptionalJobPatchResponseMeta(TypedDict, total=False):
    # The point in time for which this response is for. This date will follow the format defined by [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6).
    asAt: str

    # WARNING: This property is deprecated
    # A link to fetch all [Workflows](https://developers.intellihr.io/docs/v1/) that belong under the Workflow Event for this Job update. To be **deprecated**, it is recommended to use **workflowEventIds** to construct links.
    workflowEvent: typing.Union[str, none_type]

    # WARNING: This property is deprecated
    # The identifier string for the [Workflow Event](https://developers.intellihr.io/docs/v1/). To be **deprecated**, it is recommended to use **workflowEventIds**.
    workflowEventId: typing.Union[str, none_type]

    # List of string identifiers for [Workflow Events](https://developers.intellihr.io/docs/v1/). This will not be defined if there is no workflowEvents in the response
    workflowEventIds: typing.List[str]

    # The identifier string for the api request.
    requestId: str

class JobPatchResponseMeta(RequiredJobPatchResponseMeta, OptionalJobPatchResponseMeta):
    pass
