# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.people_update_request_addresses import PeopleUpdateRequestAddresses
from intelli_hr_python_sdk.type.people_update_request_custom_fields import PeopleUpdateRequestCustomFields
from intelli_hr_python_sdk.type.people_update_request_email_addresses import PeopleUpdateRequestEmailAddresses
from intelli_hr_python_sdk.type.people_update_request_emergency_contact import PeopleUpdateRequestEmergencyContact
from intelli_hr_python_sdk.type.people_update_request_medical_conditions import PeopleUpdateRequestMedicalConditions
from intelli_hr_python_sdk.type.people_update_request_phone_numbers import PeopleUpdateRequestPhoneNumbers

class RequiredPeopleUpdateRequest(TypedDict):
    pass

class OptionalPeopleUpdateRequest(TypedDict, total=False):
    # The title to refer to this [Person](https://developers.intellihr.io/docs/v1/) as, for example \"Mr\". This is null if not provided and is case insensitive.
    title: typing.Union[str, none_type]

    # The [Person's](https://developers.intellihr.io/docs/v1/) First Name.
    firstName: typing.Union[str, none_type]

    # The [Person's](https://developers.intellihr.io/docs/v1/) Middle Name.
    middleName: typing.Union[str, none_type]

    # The [Person's](https://developers.intellihr.io/docs/v1/) Last Name.
    lastName: str

    # The [Person's](https://developers.intellihr.io/docs/v1/) Preferred Name. Can generally be configured by employees for themselves.
    preferredName: typing.Union[str, none_type]

    # Date of Birth (YYYY-MM-DD).
    dateOfBirth: typing.Union[str, none_type]

    # Human readable string for the [Person's](https://developers.intellihr.io/docs/v1/) gender, e.g. `Male`. Searching is done case-insensitively and 'starts-with' e.g. passing `male` will match with a [Gender](https://developers.intellihr.io/docs/v1/) called \"Male\" as will \"m\" or \"M\". If multiple [Genders](https://developers.intellihr.io/docs/v1/) match the first will be chosen. The gender options available are: `Female`, `Male`, `Non-binary`, `Other`, `Undisclosed`.
    gender: str

    # A manually entered employee number that identifies a [Person](https://developers.intellihr.io/docs/v1/) in intelliHR. It may be hidden in the system's UI depending upon your tenant's configuration.
    employeeNumber: typing.Union[str, none_type]

    emergencyContact: PeopleUpdateRequestEmergencyContact

    emailAddresses: PeopleUpdateRequestEmailAddresses

    phoneNumbers: PeopleUpdateRequestPhoneNumbers

    addresses: PeopleUpdateRequestAddresses

    customFields: PeopleUpdateRequestCustomFields

    medicalConditions: PeopleUpdateRequestMedicalConditions

    # [Work Right](https://developers.intellihr.io/docs/v1/) to whom this [Person](https://developers.intellihr.io/docs/v1/) belongs. This [Work Right](https://developers.intellihr.io/docs/v1/) is specified as a search object, which will match the work right which best fits the keys for this object. Multiple keys can be used together to further narrow search results. Null can be provided to remove a person's work right.
    workRight: typing.Union[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]], none_type]

    # The date this [Work Right](https://developers.intellihr.io/docs/v1/) will expire for this [Person](https://developers.intellihr.io/docs/v1/) (YYYY-MM-DD).
    workRightExpiryDate: typing.Union[str, none_type]

class PeopleUpdateRequest(RequiredPeopleUpdateRequest, OptionalPeopleUpdateRequest):
    pass
