# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPeopleUpdateRequestMedicalConditionsItem(TypedDict):
    # The name and description of the medical condition
    body: str

class OptionalPeopleUpdateRequestMedicalConditionsItem(TypedDict, total=False):
    # If the medical condition is visible to anyone with permission to view this person's profile. Defaults to false.
    isPublic: bool

class PeopleUpdateRequestMedicalConditionsItem(RequiredPeopleUpdateRequestMedicalConditionsItem, OptionalPeopleUpdateRequestMedicalConditionsItem):
    pass
