# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.person_id_image_patch_request_coordinates import PersonIdImagePatchRequestCoordinates

class RequiredPersonIdImagePatchRequest(TypedDict):
    pass

class OptionalPersonIdImagePatchRequest(TypedDict, total=False):
    # The Image Type. Enum: `PERSON_PROFILE`, `PROFILE_COVER`.
    imageType: str

    # the degree to rotate the image from 0-359
    rotation: int

    coordinates: PersonIdImagePatchRequestCoordinates

class PersonIdImagePatchRequest(RequiredPersonIdImagePatchRequest, OptionalPersonIdImagePatchRequest):
    pass
