# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPersonIdPatchRequest(TypedDict):
    pass

class OptionalPersonIdPatchRequest(TypedDict, total=False):
    # The Skill Level you wish to apply to this Skill. Enum: `Expert`, `Proficient`, `Interested`, `Basic`.
    skillLevel: str

class PersonIdPatchRequest(RequiredPersonIdPatchRequest, OptionalPersonIdPatchRequest):
    pass
