# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPersonIdImagePatchRequestCoordinates(TypedDict):
    # the multiple to crop the height of the image to (e.g. 0.5 will half the height)
    height: int

    # the multiple to crop the width of the image to (e.g. 0.5 will half the width)
    width: int

    # the multiple to offset the x crop (e.g. 0.5 will crop to show the right side of the image if the width is also 0.5)
    x: int

    # the multiple to offset the y crop (e.g. 0.5 will crop to show the bottom of the image if the height is also 0.5)
    y: int

class OptionalPersonIdImagePatchRequestCoordinates(TypedDict, total=False):
    pass

class PersonIdImagePatchRequestCoordinates(RequiredPersonIdImagePatchRequestCoordinates, OptionalPersonIdImagePatchRequestCoordinates):
    pass
