# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.qualifications_list_data_item_library_item_qualification_type import QualificationsListDataItemLibraryItemQualificationType

class RequiredQualificationsListDataItemLibraryItem(TypedDict):
    pass

class OptionalQualificationsListDataItemLibraryItem(TypedDict, total=False):
    # The identifier string for the Qualification Library Item.
    id: str

    # Library Item name
    name: str

    qualificationType: QualificationsListDataItemLibraryItemQualificationType

    # Link on the public api to get more information on this piece of data.
    link: str

class QualificationsListDataItemLibraryItem(RequiredQualificationsListDataItemLibraryItem, OptionalQualificationsListDataItemLibraryItem):
    pass
