# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.skill_disciplines_list_data_item_skills import SkillDisciplinesListDataItemSkills

class RequiredSkillDisciplinesListDataItem(TypedDict):
    pass

class OptionalSkillDisciplinesListDataItem(TypedDict, total=False):
    # The identifier string for the [Skill Discipline](https://developers.intellihr.io/docs/v1/).
    id: str

    # The name of this [Skill Discipline](https://developers.intellihr.io/docs/v1/).
    name: str

    skills: SkillDisciplinesListDataItemSkills

class SkillDisciplinesListDataItem(RequiredSkillDisciplinesListDataItem, OptionalSkillDisciplinesListDataItem):
    pass
