# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.trainings_list_data import TrainingsListData
from intelli_hr_python_sdk.type.trainings_list_links import TrainingsListLinks
from intelli_hr_python_sdk.type.trainings_list_meta import TrainingsListMeta

class RequiredTrainingsList(TypedDict):
    pass

class OptionalTrainingsList(TypedDict, total=False):
    data: TrainingsListData

    meta: TrainingsListMeta

    links: TrainingsListLinks

class TrainingsList(RequiredTrainingsList, OptionalTrainingsList):
    pass
