# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.training_providers_list_data import TrainingProvidersListData
from intelli_hr_python_sdk.type.training_providers_list_links import TrainingProvidersListLinks
from intelli_hr_python_sdk.type.training_providers_list_meta import TrainingProvidersListMeta

class RequiredTrainingProvidersList(TypedDict):
    pass

class OptionalTrainingProvidersList(TypedDict, total=False):
    data: TrainingProvidersListData

    meta: TrainingProvidersListMeta

    links: TrainingProvidersListLinks

class TrainingProvidersList(RequiredTrainingProvidersList, OptionalTrainingProvidersList):
    pass
