# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.users_list_meta_pagination import UsersListMetaPagination

class RequiredUsersListMeta(TypedDict):
    pass

class OptionalUsersListMeta(TypedDict, total=False):
    pagination: UsersListMetaPagination

    # The identifier string for the api request.
    requestId: str

class UsersListMeta(RequiredUsersListMeta, OptionalUsersListMeta):
    pass
