# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.webhook_events_list_data import WebhookEventsListData
from intelli_hr_python_sdk.type.webhook_events_list_links import WebhookEventsListLinks
from intelli_hr_python_sdk.type.webhook_events_list_meta import WebhookEventsListMeta

class RequiredWebhookEventsList(TypedDict):
    pass

class OptionalWebhookEventsList(TypedDict, total=False):
    data: WebhookEventsListData

    meta: WebhookEventsListMeta

    links: WebhookEventsListLinks

class WebhookEventsList(RequiredWebhookEventsList, OptionalWebhookEventsList):
    pass
