# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from intelli_hr_python_sdk.type.work_classes_list_data import WorkClassesListData
from intelli_hr_python_sdk.type.work_classes_list_links import WorkClassesListLinks
from intelli_hr_python_sdk.type.work_classes_list_meta import WorkClassesListMeta

class RequiredWorkClassesList(TypedDict):
    pass

class OptionalWorkClassesList(TypedDict, total=False):
    data: WorkClassesListData

    meta: WorkClassesListMeta

    links: WorkClassesListLinks

class WorkClassesList(RequiredWorkClassesList, OptionalWorkClassesList):
    pass
