# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from intelli_hr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from intelli_hr_python_sdk.api_response import AsyncGeneratorResponse
from intelli_hr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from intelli_hr_python_sdk import schemas  # noqa: F401

from intelli_hr_python_sdk.model.jobs_list import JobsList as JobsListSchema

from intelli_hr_python_sdk.type.jobs_list import JobsList

from ...api_client import Dictionary
from intelli_hr_python_sdk.pydantic.jobs_list import JobsList as JobsListPydantic

# Query params


class FiltersSchema(
    schemas.DictSchema
):


    class MetaOapg:
        
        class properties:
            
            
            class personId(
                schemas.StrSchema
            ):
                pass
            personName = schemas.StrSchema
            primaryEmail = schemas.StrSchema
            employeeNumber = schemas.StrSchema
            autoIncrementIntellihrId = schemas.NumberSchema
            jobId = schemas.StrSchema
            jobName = schemas.StrSchema
            jobNameAsAt = schemas.StrSchema
            jobStatus = schemas.StrSchema
            jobEndingWithin = schemas.StrSchema
            jobEndedWithin = schemas.StrSchema
            updatedWithin = schemas.StrSchema
            workType = schemas.StrSchema
            isPrimaryJob = schemas.StrSchema
            
            
            class employmentConditionId(
                schemas.StrSchema
            ):
                pass
            __annotations__ = {
                "personId": personId,
                "personName": personName,
                "primaryEmail": primaryEmail,
                "employeeNumber": employeeNumber,
                "autoIncrementIntellihrId": autoIncrementIntellihrId,
                "jobId": jobId,
                "jobName": jobName,
                "jobNameAsAt": jobNameAsAt,
                "jobStatus": jobStatus,
                "jobEndingWithin": jobEndingWithin,
                "jobEndedWithin": jobEndedWithin,
                "updatedWithin": updatedWithin,
                "workType": workType,
                "isPrimaryJob": isPrimaryJob,
                "employmentConditionId": employmentConditionId,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personId"]) -> MetaOapg.properties.personId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personName"]) -> MetaOapg.properties.personName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["primaryEmail"]) -> MetaOapg.properties.primaryEmail: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employeeNumber"]) -> MetaOapg.properties.employeeNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["autoIncrementIntellihrId"]) -> MetaOapg.properties.autoIncrementIntellihrId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobId"]) -> MetaOapg.properties.jobId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobName"]) -> MetaOapg.properties.jobName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobNameAsAt"]) -> MetaOapg.properties.jobNameAsAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobStatus"]) -> MetaOapg.properties.jobStatus: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobEndingWithin"]) -> MetaOapg.properties.jobEndingWithin: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobEndedWithin"]) -> MetaOapg.properties.jobEndedWithin: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updatedWithin"]) -> MetaOapg.properties.updatedWithin: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["workType"]) -> MetaOapg.properties.workType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isPrimaryJob"]) -> MetaOapg.properties.isPrimaryJob: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employmentConditionId"]) -> MetaOapg.properties.employmentConditionId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["personId", "personName", "primaryEmail", "employeeNumber", "autoIncrementIntellihrId", "jobId", "jobName", "jobNameAsAt", "jobStatus", "jobEndingWithin", "jobEndedWithin", "updatedWithin", "workType", "isPrimaryJob", "employmentConditionId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personId"]) -> typing.Union[MetaOapg.properties.personId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personName"]) -> typing.Union[MetaOapg.properties.personName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["primaryEmail"]) -> typing.Union[MetaOapg.properties.primaryEmail, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employeeNumber"]) -> typing.Union[MetaOapg.properties.employeeNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["autoIncrementIntellihrId"]) -> typing.Union[MetaOapg.properties.autoIncrementIntellihrId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobId"]) -> typing.Union[MetaOapg.properties.jobId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobName"]) -> typing.Union[MetaOapg.properties.jobName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobNameAsAt"]) -> typing.Union[MetaOapg.properties.jobNameAsAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobStatus"]) -> typing.Union[MetaOapg.properties.jobStatus, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobEndingWithin"]) -> typing.Union[MetaOapg.properties.jobEndingWithin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobEndedWithin"]) -> typing.Union[MetaOapg.properties.jobEndedWithin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updatedWithin"]) -> typing.Union[MetaOapg.properties.updatedWithin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["workType"]) -> typing.Union[MetaOapg.properties.workType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isPrimaryJob"]) -> typing.Union[MetaOapg.properties.isPrimaryJob, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employmentConditionId"]) -> typing.Union[MetaOapg.properties.employmentConditionId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["personId", "personName", "primaryEmail", "employeeNumber", "autoIncrementIntellihrId", "jobId", "jobName", "jobNameAsAt", "jobStatus", "jobEndingWithin", "jobEndedWithin", "updatedWithin", "workType", "isPrimaryJob", "employmentConditionId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        personId: typing.Union[MetaOapg.properties.personId, str, schemas.Unset] = schemas.unset,
        personName: typing.Union[MetaOapg.properties.personName, str, schemas.Unset] = schemas.unset,
        primaryEmail: typing.Union[MetaOapg.properties.primaryEmail, str, schemas.Unset] = schemas.unset,
        employeeNumber: typing.Union[MetaOapg.properties.employeeNumber, str, schemas.Unset] = schemas.unset,
        autoIncrementIntellihrId: typing.Union[MetaOapg.properties.autoIncrementIntellihrId, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        jobId: typing.Union[MetaOapg.properties.jobId, str, schemas.Unset] = schemas.unset,
        jobName: typing.Union[MetaOapg.properties.jobName, str, schemas.Unset] = schemas.unset,
        jobNameAsAt: typing.Union[MetaOapg.properties.jobNameAsAt, str, schemas.Unset] = schemas.unset,
        jobStatus: typing.Union[MetaOapg.properties.jobStatus, str, schemas.Unset] = schemas.unset,
        jobEndingWithin: typing.Union[MetaOapg.properties.jobEndingWithin, str, schemas.Unset] = schemas.unset,
        jobEndedWithin: typing.Union[MetaOapg.properties.jobEndedWithin, str, schemas.Unset] = schemas.unset,
        updatedWithin: typing.Union[MetaOapg.properties.updatedWithin, str, schemas.Unset] = schemas.unset,
        workType: typing.Union[MetaOapg.properties.workType, str, schemas.Unset] = schemas.unset,
        isPrimaryJob: typing.Union[MetaOapg.properties.isPrimaryJob, str, schemas.Unset] = schemas.unset,
        employmentConditionId: typing.Union[MetaOapg.properties.employmentConditionId, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FiltersSchema':
        return super().__new__(
            cls,
            *args,
            personId=personId,
            personName=personName,
            primaryEmail=primaryEmail,
            employeeNumber=employeeNumber,
            autoIncrementIntellihrId=autoIncrementIntellihrId,
            jobId=jobId,
            jobName=jobName,
            jobNameAsAt=jobNameAsAt,
            jobStatus=jobStatus,
            jobEndingWithin=jobEndingWithin,
            jobEndedWithin=jobEndedWithin,
            updatedWithin=updatedWithin,
            workType=workType,
            isPrimaryJob=isPrimaryJob,
            employmentConditionId=employmentConditionId,
            _configuration=_configuration,
            **kwargs,
        )
SortSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'filters': typing.Union[FiltersSchema, dict, frozendict.frozendict, ],
        'sort': typing.Union[SortSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_filters = api_client.QueryParameter(
    name="filters",
    style=api_client.ParameterStyle.FORM,
    schema=FiltersSchema,
    explode=True,
)
request_query_sort = api_client.QueryParameter(
    name="sort",
    style=api_client.ParameterStyle.FORM,
    schema=SortSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = JobsListSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: JobsList


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: JobsList


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_all_mapped_args(
        self,
        filters: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        sort: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if filters is not None:
            _query_params["filters"] = filters
        if sort is not None:
            _query_params["sort"] = sort
        args.query = _query_params
        return args

    async def _aget_all_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        List all Jobs
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_filters,
            request_query_sort,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/jobs',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_all_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        List all Jobs
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_filters,
            request_query_sort,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/jobs',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetAllRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_all(
        self,
        filters: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        sort: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_all_mapped_args(
            filters=filters,
            sort=sort,
        )
        return await self._aget_all_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_all(
        self,
        filters: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        sort: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_all_mapped_args(
            filters=filters,
            sort=sort,
        )
        return self._get_all_oapg(
            query_params=args.query,
        )

class GetAll(BaseApi):

    async def aget_all(
        self,
        filters: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        sort: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> JobsListPydantic:
        raw_response = await self.raw.aget_all(
            filters=filters,
            sort=sort,
            **kwargs,
        )
        if validate:
            return JobsListPydantic(**raw_response.body)
        return api_client.construct_model_instance(JobsListPydantic, raw_response.body)
    
    
    def get_all(
        self,
        filters: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        sort: typing.Optional[str] = None,
        validate: bool = False,
    ) -> JobsListPydantic:
        raw_response = self.raw.get_all(
            filters=filters,
            sort=sort,
        )
        if validate:
            return JobsListPydantic(**raw_response.body)
        return api_client.construct_model_instance(JobsListPydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        filters: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        sort: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_all_mapped_args(
            filters=filters,
            sort=sort,
        )
        return await self._aget_all_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        filters: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        sort: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_all_mapped_args(
            filters=filters,
            sort=sort,
        )
        return self._get_all_oapg(
            query_params=args.query,
        )

