# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from intelli_hr_python_sdk.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    BUSINESS_ENTITIES = "Business Entities"
    BUSINESS_UNITS = "Business Units"
    CUSTOM_FIELD_DEFINITIONS = "Custom Field Definitions"
    JOB_CHANGE_REASONS = "Job Change Reasons"
    JOB_REQUIREMENT_GROUPS = "Job Requirement Groups"
    LOCATIONS = "Locations"
    PAY_GRADES = "Pay Grades"
    PEOPLE_SKILLS = "People Skills"
    QUALIFICATION_INSTANCES = "Qualification Instances"
    QUALIFICATION_LIBRARY_ITEMS = "Qualification Library Items"
    TRAININGS = "Trainings"
    WEBHOOKS = "Webhooks"
    JOBS = "Jobs"
    PEOPLE = "People"
    POSITION_TITLES = "Position Titles"
    SKILLS = "Skills"
    SKILL_DISCIPLINES = "Skill Disciplines"
    USERS = "Users"
    PEOPLE_IMAGES = "People Images"
    PEOPLE_DOCUMENTS = "People Documents"
    DEFAULT_REMUNERATION_COMPONENTS = "Default Remuneration Components"
    EMPLOYMENT_CONDITIONS = "Employment Conditions"
    EXTENDED_LEAVE = "Extended Leave"
    EXTENDED_LEAVE_TYPES = "Extended Leave Types"
    END_JOB = "End Job"
    PERMISSION_GROUPS = "Permission Groups"
    PERSON_DOCUMENTS_DEPRECATED = "Person Documents (deprecated)"
    QUALIFICATION_TYPES = "Qualification Types"
    RECRUITMENT_SOURCES = "Recruitment Sources"
    REPRESENTATIVE_TYPES = "Representative Types"
    TRAINING_PROVIDERS = "Training Providers"
    TRAINING_TYPES = "Training Types"
    WORK_CLASSES = "Work Classes"
    WORK_RIGHTS = "Work Rights"
    WORK_TYPES = "Work Types"
    WEBHOOK_EVENTS = "Webhook Events"
    FORMS = "Forms"
    JOB_TIMELINE = "Job Timeline"
    QUALIFICATION_STATUSES = "Qualification Statuses"
    TRAINING_STATUSES = "Training Statuses"
    WORKFLOW_EVENTS = "Workflow Events"
    WORKFLOWS = "Workflows"
