# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.business_units.post import CreateNewUnitRaw
from intelli_hr_python_sdk.paths.business_units_id.delete import DeleteByIdRaw
from intelli_hr_python_sdk.paths.business_units_id.get import FindByIdRaw
from intelli_hr_python_sdk.paths.business_units.get import ListAllRaw
from intelli_hr_python_sdk.paths.business_units_id.patch import UpdateByIdRaw


class BusinessUnitsApiRaw(
    CreateNewUnitRaw,
    DeleteByIdRaw,
    FindByIdRaw,
    ListAllRaw,
    UpdateByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
