# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.business_entities.post import CreateNewEntity
from intelli_hr_python_sdk.paths.business_entities_id.delete import DeleteById
from intelli_hr_python_sdk.paths.business_entities_id.get import FindById
from intelli_hr_python_sdk.paths.business_entities.get import ListAll
from intelli_hr_python_sdk.paths.business_entities_id.patch import UpdateById
from intelli_hr_python_sdk.apis.tags.business_entities_api_raw import BusinessEntitiesApiRaw


class BusinessEntitiesApi(
    CreateNewEntity,
    DeleteById,
    FindById,
    ListAll,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BusinessEntitiesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BusinessEntitiesApiRaw(api_client)
