# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.employment_conditions_id.get import FindById
from intelli_hr_python_sdk.paths.employment_conditions.get import ListAllEmploymentConditions
from intelli_hr_python_sdk.apis.tags.employment_conditions_api_raw import EmploymentConditionsApiRaw


class EmploymentConditionsApi(
    FindById,
    ListAllEmploymentConditions,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmploymentConditionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmploymentConditionsApiRaw(api_client)
