# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.jobs_job_id_timeline.get import GetUpcomingChanges
from intelli_hr_python_sdk.apis.tags.job_timeline_api_raw import JobTimelineApiRaw


class JobTimelineApi(
    GetUpcomingChanges,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobTimelineApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobTimelineApiRaw(api_client)
