# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.jobs.post import CreateRecord
from intelli_hr_python_sdk.paths.jobs_id.get import FindById
from intelli_hr_python_sdk.paths.jobs.get import GetAll
from intelli_hr_python_sdk.paths.jobs_id.patch import UpdateAttributes
from intelli_hr_python_sdk.apis.tags.jobs_api_raw import JobsApiRaw


class JobsApi(
    CreateRecord,
    FindById,
    GetAll,
    UpdateAttributes,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobsApiRaw(api_client)
