# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.people_person_id_images.post import GenerateTemporaryImageUrl
from intelli_hr_python_sdk.paths.people_person_id_images.get import GetTemporaryImage
from intelli_hr_python_sdk.paths.people_person_id_images.patch import PromoteImage
from intelli_hr_python_sdk.apis.tags.people_images_api_raw import PeopleImagesApiRaw


class PeopleImagesApi(
    GenerateTemporaryImageUrl,
    GetTemporaryImage,
    PromoteImage,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PeopleImagesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PeopleImagesApiRaw(api_client)
