# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.people_person_id_skills.post import AssignSkillToPerson
from intelli_hr_python_sdk.paths.people_person_id_skills_id.delete import DeleteAssignedSkillById
from intelli_hr_python_sdk.paths.people_person_id_skills_id.get import FindSkillById
from intelli_hr_python_sdk.paths.people_person_id_skills.get import ListPersonSkills
from intelli_hr_python_sdk.paths.people_person_id_skills_id.patch import UpdateAssignedSkill
from intelli_hr_python_sdk.apis.tags.people_skills_api_raw import PeopleSkillsApiRaw


class PeopleSkillsApi(
    AssignSkillToPerson,
    DeleteAssignedSkillById,
    FindSkillById,
    ListPersonSkills,
    UpdateAssignedSkill,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PeopleSkillsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PeopleSkillsApiRaw(api_client)
