# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.qualification_library_items.post import CreateNewRecord
from intelli_hr_python_sdk.paths.qualification_library_items_id.delete import DeleteById
from intelli_hr_python_sdk.paths.qualification_library_items_id.get import FindById
from intelli_hr_python_sdk.paths.qualification_library_items.get import GetAllQualifications
from intelli_hr_python_sdk.paths.qualification_library_items_id.patch import UpdateRecord
from intelli_hr_python_sdk.apis.tags.qualification_library_items_api_raw import QualificationLibraryItemsApiRaw


class QualificationLibraryItemsApi(
    CreateNewRecord,
    DeleteById,
    FindById,
    GetAllQualifications,
    UpdateRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: QualificationLibraryItemsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = QualificationLibraryItemsApiRaw(api_client)
