# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.trainings.post import CreateNewTrainingRaw
from intelli_hr_python_sdk.paths.trainings_id.delete import DeleteByIdRaw
from intelli_hr_python_sdk.paths.trainings_id.get import FindTrainingByIdRaw
from intelli_hr_python_sdk.paths.trainings.get import ListAllRaw
from intelli_hr_python_sdk.paths.trainings_id.patch import UpdateTrainingByIdRaw


class TrainingsApiRaw(
    CreateNewTrainingRaw,
    DeleteByIdRaw,
    FindTrainingByIdRaw,
    ListAllRaw,
    UpdateTrainingByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
