# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from intelli_hr_python_sdk.paths.webhook_events_id.get import FindEventById
from intelli_hr_python_sdk.paths.webhook_events.get import ListAllEvents
from intelli_hr_python_sdk.apis.tags.webhook_events_api_raw import WebhookEventsApiRaw


class WebhookEventsApi(
    FindEventById,
    ListAllEvents,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WebhookEventsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WebhookEventsApiRaw(api_client)
