# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import intelli_hr_python_sdk
from intelli_hr_python_sdk.paths.business_units import post
from intelli_hr_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestBusinessUnits(ApiTestMixin, unittest.TestCase):
    """
    BusinessUnits unit test stubs
        Create a new Business Unit
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 201






if __name__ == '__main__':
    unittest.main()
