# coding: utf-8

"""
    intelliHR Public API

    You can find developer's guide and more documentation on [https://developers.intellihr.io](https://developers.intellihr.io)

    The version of the OpenAPI document: V1
    Contact: support@intellihr.co
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from intelli_hr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from intelli_hr_python_sdk.api_response import AsyncGeneratorResponse
from intelli_hr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from intelli_hr_python_sdk import schemas  # noqa: F401

from intelli_hr_python_sdk.model.qualification_instances_create_request import QualificationInstancesCreateRequest as QualificationInstancesCreateRequestSchema
from intelli_hr_python_sdk.model.qualifications import Qualifications as QualificationsSchema

from intelli_hr_python_sdk.type.qualifications import Qualifications
from intelli_hr_python_sdk.type.qualification_instances_create_request import QualificationInstancesCreateRequest

from ...api_client import Dictionary
from intelli_hr_python_sdk.pydantic.qualifications import Qualifications as QualificationsPydantic
from intelli_hr_python_sdk.pydantic.qualification_instances_create_request import QualificationInstancesCreateRequest as QualificationInstancesCreateRequestPydantic

# body param
SchemaForRequestBodyApplicationJson = QualificationInstancesCreateRequestSchema


request_body_qualification_instances_create_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
SchemaFor201ResponseBodyApplicationJson = QualificationsSchema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: Qualifications


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: Qualifications


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
)


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
)


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_new_instance_mapped_args(
        self,
        person_id: str,
        qualification_library_item_id: str,
        status: str,
        issuing_organisation: typing.Optional[typing.Union[str, none_type]] = None,
        registration_number: typing.Optional[typing.Union[str, none_type]] = None,
        issue_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_notification_queued_at: typing.Optional[typing.Union[str, none_type]] = None,
        notes: typing.Optional[typing.Union[str, none_type]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if person_id is not None:
            _body["personId"] = person_id
        if qualification_library_item_id is not None:
            _body["qualificationLibraryItemId"] = qualification_library_item_id
        if status is not None:
            _body["status"] = status
        if issuing_organisation is not None:
            _body["issuingOrganisation"] = issuing_organisation
        if registration_number is not None:
            _body["registrationNumber"] = registration_number
        if issue_date is not None:
            _body["issueDate"] = issue_date
        if expiry_date is not None:
            _body["expiryDate"] = expiry_date
        if expiry_notification_queued_at is not None:
            _body["expiryNotificationQueuedAt"] = expiry_notification_queued_at
        if notes is not None:
            _body["notes"] = notes
        args.body = _body
        return args

    async def _acreate_new_instance_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create a new Qualification Instance
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/qualifications',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_qualification_instances_create_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_new_instance_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create a new Qualification Instance
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/qualifications',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_qualification_instances_create_request.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateNewInstanceRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_new_instance(
        self,
        person_id: str,
        qualification_library_item_id: str,
        status: str,
        issuing_organisation: typing.Optional[typing.Union[str, none_type]] = None,
        registration_number: typing.Optional[typing.Union[str, none_type]] = None,
        issue_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_notification_queued_at: typing.Optional[typing.Union[str, none_type]] = None,
        notes: typing.Optional[typing.Union[str, none_type]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_instance_mapped_args(
            person_id=person_id,
            qualification_library_item_id=qualification_library_item_id,
            status=status,
            issuing_organisation=issuing_organisation,
            registration_number=registration_number,
            issue_date=issue_date,
            expiry_date=expiry_date,
            expiry_notification_queued_at=expiry_notification_queued_at,
            notes=notes,
        )
        return await self._acreate_new_instance_oapg(
            body=args.body,
            **kwargs,
        )
    
    def create_new_instance(
        self,
        person_id: str,
        qualification_library_item_id: str,
        status: str,
        issuing_organisation: typing.Optional[typing.Union[str, none_type]] = None,
        registration_number: typing.Optional[typing.Union[str, none_type]] = None,
        issue_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_notification_queued_at: typing.Optional[typing.Union[str, none_type]] = None,
        notes: typing.Optional[typing.Union[str, none_type]] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_instance_mapped_args(
            person_id=person_id,
            qualification_library_item_id=qualification_library_item_id,
            status=status,
            issuing_organisation=issuing_organisation,
            registration_number=registration_number,
            issue_date=issue_date,
            expiry_date=expiry_date,
            expiry_notification_queued_at=expiry_notification_queued_at,
            notes=notes,
        )
        return self._create_new_instance_oapg(
            body=args.body,
        )

class CreateNewInstance(BaseApi):

    async def acreate_new_instance(
        self,
        person_id: str,
        qualification_library_item_id: str,
        status: str,
        issuing_organisation: typing.Optional[typing.Union[str, none_type]] = None,
        registration_number: typing.Optional[typing.Union[str, none_type]] = None,
        issue_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_notification_queued_at: typing.Optional[typing.Union[str, none_type]] = None,
        notes: typing.Optional[typing.Union[str, none_type]] = None,
        validate: bool = False,
        **kwargs,
    ) -> QualificationsPydantic:
        raw_response = await self.raw.acreate_new_instance(
            person_id=person_id,
            qualification_library_item_id=qualification_library_item_id,
            status=status,
            issuing_organisation=issuing_organisation,
            registration_number=registration_number,
            issue_date=issue_date,
            expiry_date=expiry_date,
            expiry_notification_queued_at=expiry_notification_queued_at,
            notes=notes,
            **kwargs,
        )
        if validate:
            return QualificationsPydantic(**raw_response.body)
        return api_client.construct_model_instance(QualificationsPydantic, raw_response.body)
    
    
    def create_new_instance(
        self,
        person_id: str,
        qualification_library_item_id: str,
        status: str,
        issuing_organisation: typing.Optional[typing.Union[str, none_type]] = None,
        registration_number: typing.Optional[typing.Union[str, none_type]] = None,
        issue_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_notification_queued_at: typing.Optional[typing.Union[str, none_type]] = None,
        notes: typing.Optional[typing.Union[str, none_type]] = None,
        validate: bool = False,
    ) -> QualificationsPydantic:
        raw_response = self.raw.create_new_instance(
            person_id=person_id,
            qualification_library_item_id=qualification_library_item_id,
            status=status,
            issuing_organisation=issuing_organisation,
            registration_number=registration_number,
            issue_date=issue_date,
            expiry_date=expiry_date,
            expiry_notification_queued_at=expiry_notification_queued_at,
            notes=notes,
        )
        if validate:
            return QualificationsPydantic(**raw_response.body)
        return api_client.construct_model_instance(QualificationsPydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        person_id: str,
        qualification_library_item_id: str,
        status: str,
        issuing_organisation: typing.Optional[typing.Union[str, none_type]] = None,
        registration_number: typing.Optional[typing.Union[str, none_type]] = None,
        issue_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_notification_queued_at: typing.Optional[typing.Union[str, none_type]] = None,
        notes: typing.Optional[typing.Union[str, none_type]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_new_instance_mapped_args(
            person_id=person_id,
            qualification_library_item_id=qualification_library_item_id,
            status=status,
            issuing_organisation=issuing_organisation,
            registration_number=registration_number,
            issue_date=issue_date,
            expiry_date=expiry_date,
            expiry_notification_queued_at=expiry_notification_queued_at,
            notes=notes,
        )
        return await self._acreate_new_instance_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        person_id: str,
        qualification_library_item_id: str,
        status: str,
        issuing_organisation: typing.Optional[typing.Union[str, none_type]] = None,
        registration_number: typing.Optional[typing.Union[str, none_type]] = None,
        issue_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_date: typing.Optional[typing.Union[str, none_type]] = None,
        expiry_notification_queued_at: typing.Optional[typing.Union[str, none_type]] = None,
        notes: typing.Optional[typing.Union[str, none_type]] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_new_instance_mapped_args(
            person_id=person_id,
            qualification_library_item_id=qualification_library_item_id,
            status=status,
            issuing_organisation=issuing_organisation,
            registration_number=registration_number,
            issue_date=issue_date,
            expiry_date=expiry_date,
            expiry_notification_queued_at=expiry_notification_queued_at,
            notes=notes,
        )
        return self._create_new_instance_oapg(
            body=args.body,
        )

